version: '3.4'

#common
x-api-service:
  &default_api_service
  image: vladraven/otus_grad_api_service
  build:
    context: .
    dockerfile: ApiDockerfile
  ports:
    - 5000:5000

services:
  api_service_latest:
    *default_api_service
  
  api_service_current:
    << : *default_api_service
    image: vladraven/otus_grad_api_service:0.1

    
