version: '3.4'

#common
x-auth-service:
  &default_auth_service
  image: vladraven/otus_grad_auth_service
  build:
    context: .
    dockerfile: AuthDockerfile
  ports:
    - 5000:5000

services:
  auth_service_latest:
    *default_auth_service
  
  auth_service_current:
    << : *default_auth_service
    image: vladraven/otus_grad_auth_service:0.1

    