version: '3.4'

#common
x-projects-service:
  &default_projects_service
  image: vladraven/otus_projects_service
  build:
    context: .
    dockerfile: ProjectsDockerfile
  ports:
    - 5000:5000

services:
  projects_service_latest:
    *default_projects_service
  
  projects_service_current:
    << : *default_projects_service
    image: vladraven/otus_projects_service:0.1

    