docker-compose -f api-docker-compose.yml build
docker-compose -f auth-docker-compose.yml build
docker-compose -f labels-docker-compose.yml build
docker-compose -f lists-docker-compose.yml build
docker-compose -f notifications-docker-compose.yml build
docker-compose -f project-members-docker-compose.yml build
docker-compose -f projects-docker-compose.yml build
docker-compose -f tasks-docker-compose.yml build
docker-compose -f users-docker-compose.yml build
docker-compose -f working-hours-docker-compose.yml build
