apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tasks-chart.fullname" . }}
type: Opaque
data:
  PG_CONNECTION:  {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword  .Values.postgresql.fullnameOverride .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}  