apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  "{{ include "auth-chart.fullname" . }}-ss"
spec:
  serviceName: "{{ .Values.ravendb.host }}"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ravendb.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.ravendb.label }}
    spec:
      containers:
      - name: {{ .Values.ravendb.label }}
        image: ravendb/ravendb:latest
        ports:
        - containerPort: {{ .Values.ravendb.intport }}
          name: ravendbport
        env:
          - name: RAVEN_ARGS
            value: '--Setup.Mode=None --License.Eula.Accepted=true'
        volumeMounts:
        - name: auth-ravendb
          mountPath: /opt/RavenDB/Server/RavenData
          subPath: auth_info
  volumeClaimTemplates:
  - metadata:
      name: auth-ravendb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi