version: '3.4'

#common
x-users-service:
  &default_users_service
  image: vladraven/otus_users_service
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - 5003:5003

services:
  users_service_latest:
    *default_users_service
  
  users_service_current:
    << : *default_users_service
    image: vladraven/otus_users_service:0.2
    