apiVersion: batch/v1
kind: Job
metadata:
  name: tasks-service-stress-job
spec:
  template:
    metadata:
      name: postgres
    spec:
      restartPolicy: Never
      containers:
       - name: stress-tasks-job 
         image: vladraven/otus_bomber_service
         env:
         - name: TARGET_HOST_NAME
           value: arch.homework
         - name: TARGET_HOST_URL
           value: nginx-nginx-ingress-controller
         - name: RPS
           value: "20"
         - name: STREAM_COUNT
           value: "2"

  backoffLimit: 0
