{
 "title": "Tasks locust",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)\n(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"+Inf\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"tasks\"}",
     "legendFormat": "Connections count"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))",
     "legendFormat": "Q0.5"
    },
    {
     "expr": "histogram_quantile(0.9, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))",
     "legendFormat": "Q0.9"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))",
     "legendFormat": "Q0.95"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"tasks-chart\"}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "Service"
    }
   ]
  },
  {
   "title": "Containers RAM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"tasks-chart\"}) by (pod) / 1000000",
     "legendFormat": "{{pod}}, mb"
    }
   ]
  },
  {
   "title": "PODs RAM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\".*-tasks-chart-.*\"}) by (pod) / 1000000",
     "legendFormat": "{{pod}}, mb"
    }
   ]
  }
 ]
}