apiVersion: v1
kind: Service
metadata:
    name: soft-arch-hw2-serv
spec:
    selector:
        app: soft-arch-hw2
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 8000
    type: NodePort
