helm uninstall myauth
helm install mytasks
helm uninstall myusers
helm uninstall mylabels
helm uninstall mylists
helm uninstall myprojmembers
helm uninstall myprojects
helm uninstall myworkhours
helm uninstall myapi
helm uninstall rabbit
helm uninstall prometh
