helm uninstall myauth
helm uninstall mytasks
helm uninstall myusers
helm uninstall mylabels
helm uninstall mylists
helm uninstall myprojmembers
helm uninstall myprojects
helm uninstall myworkhours
helm uninstall mynotif
helm uninstall myapi
helm uninstall rabbit
helm uninstall prometh
helm uninstall cn-users 
helm uninstall eu-users 
helm uninstall ru-users 
helm uninstall us-users 
