apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-chart.fullname" . }}
  labels:
    {{- include "users-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "users-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "users-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "users-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
       - name: wait-rabbit-ready
         image: busybox:latest
         env:
         - name: RABBIT_HOST
           value: {{ .Values.rabbitMq.host }}          
         command: ['sh', '-c', 'until nslookup $RABBIT_HOST; do echo waiting for $RABBIT_HOST; sleep 2; done;']   
       - name: wait-ravendb-ready
         image: busybox:latest
         env:
          - name: RAVENDB_HOST
            value: {{ .Values.ravendb.host }}          
         command: ['sh', '-c', 'until nslookup $RAVENDB_HOST; do echo waiting for $RAVENDB_HOST; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: {{ .Values.image.dbConnectionStringEnvName }}
              value: "http://{{ .Values.ravendb.host }}:{{ .Values.ravendb.extport }}"
            - name: {{ .Values.image.authServiceUrlEnvName }}
              value: "http://{{ .Values.authService.url }}:{{ .Values.authService.port }}"
            - name: {{ .Values.rabbitMq.hostEnvName }}
              value: "{{ .Values.rabbitMq.host }}.default.svc"
            - name: {{ .Values.rabbitMq.portEnvName }}
              value: "{{ .Values.rabbitMq.port }}"
            - name: {{ .Values.rabbitMq.usernameEnvName }}
              value: {{ .Values.rabbitMq.username }}
            - name: {{ .Values.rabbitMq.passwordEnvName }}
              value: {{ .Values.rabbitMq.password }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
