version: '3.4'

services:
  otus_softarch_hw1:
    image: vladraven/otus_softarch_hw1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

    