{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "labels-chart.fullname" . }}
  labels: 
    {{- include "labels-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "labels-chart.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "labels-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: http
    path: /metrics
{{- end }}
