{
 "title": "Tasks service797",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (status)\n(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "5xx count"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Get RPS Nginx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Create RPS Nginx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Update RPS Nginx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Delete RPS Nginx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"+Inf\"}[1m]))",
     "legendFormat": "Total RPS Nginx"
    }
   ]
  },
  {
   "title": "Database",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "Is Alive" },
    {
     "expr": "pg_stat_database_numbackends{datname=\"projectsApp\"}",
     "legendFormat": "Connected backends"
    },
    {
     "expr": "pg_stat_database_conflicts{datname=\"projectsApp\"}",
     "legendFormat": "Conflicts count"
    },
    {
     "expr": "increase(pg_stat_database_tup_updated{datname=\"projectsApp\"}[1m])",
     "legendFormat": "Updated row per min"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)\n(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "Nginx-5xx"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(topk(1, sum(rate(container_cpu_usage_seconds_total{container=\"tasks-chart\"}[2m])) by (pod))) # / on() rate(node_cpu_usage_seconds_total[2m])",
     "legendFormat": "Pod 1"
    },
    {
     "expr": "(bottomk(1, sum(rate(container_cpu_usage_seconds_total{container=\"tasks-chart\"}[2m])) by (pod)))# / on() rate(node_cpu_usage_seconds_total[2m])",
     "legendFormat": "Pod 2"
    },
    {
     "expr": "rate(node_cpu_usage_seconds_total[2m])",
     "legendFormat": "Node Total"
    }
   ]
  },
  {
   "title": "RPS Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Get (all + single)"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"+Inf\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RPS Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{method=\"GET\",controller=\"Tasks\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Get single"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{action=\"GetTasks\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Get all"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{action=\"CreateTask\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{action=\"UpdateTask\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{action=\"DeleteTask\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{controller=\"Tasks\", le=\"+Inf\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\".*-tasks-chart-.*\"}[2m]) unless  rate(container_memory_usage_bytes{pod=~\".*-pg-exp-.*\"}[2m])) by (pod) / 1000000",
     "legendFormat": "Pod {{pod}}, mb"
    }
   ]
  },
  {
   "title": "Latency Create Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Create Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"CreateTask\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"CreateTask\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"CreateTask\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"CreateTask\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Get Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Update Nginx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Update Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"UpdateTask\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"UpdateTask\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"UpdateTask\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"UpdateTask\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Get Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(http_request_duration_seconds_bucket{controller=\"Tasks\", method=\"GET\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(http_request_duration_seconds_bucket{controller=\"Tasks\", method=\"GET\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(http_request_duration_seconds_bucket{controller=\"Tasks\", method=\"GET\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(http_request_duration_seconds_bucket{controller=\"Tasks\", method=\"GET\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Delete Nginx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency Delete Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"DeleteTask\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"DeleteTask\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"DeleteTask\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le)\n(rate(http_request_duration_seconds_bucket{action=\"DeleteTask\"}[1m]))))",
     "legendFormat": "max"
    }
   ]
  }
 ]
}