apiVersion: v1
kind: Service
metadata:
    name: tasks-service-serv
spec:
    selector:
        app: tasks-service
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 5000
    type: NodePort
