apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-chart.fullname" . }}
data:
  ENDPOINTS: "Project members @ http://arch.homework/otusapp/project-members/swagger/v1/swagger.json, Pets @ https://petstore.swagger.io/v2/swagger.json"